### ISSUE TITLE
请求帮助

### ISSUE THREAD

**Issue by How-Will** [teetyler/STL-LSTM#1]
老师你好，我对你在博士毕业论文中所提到的数据补全方法非常感兴趣，想要将其作为对比实验。请问能否提供代码借我参考下，不胜感激

**Comment by teetyler** [comment]
你需要处理的数据也是时间序列数据吗？当时参考的数据缺失值插补算法主要参考了ARCH算法的使用，可以参考构建有缺失值的时序数据和真实缺失的时序数据，算法在这两类数据集上的效果。
参考链接：1、方法介绍 http://mp.weixin.qq.com/s?__biz=MzI3NjQyODEwOA==&mid=2247484033&idx=1&sn=48256c2d76f041d90af062d9d6e3526e&chksm=eb74e6a2dc036fb4b313078c91af454ecbfb0d26c6f85a755a6057df0521c7f09456a450f419&mpshare=1&scene=24&srcid=0214rMEyerJDJp4uxP5Kd0fv&sharer_sharetime=1676360870413&sharer_shareid=612060fd3245f0de8059529328c96575#rd
2、代码实践 https://github.com/bashtage/arch

**Comment by How-Will** [comment]
感谢您的帮助
